
package dreamco;

import javax.swing.JOptionPane;

/**
 *
 * @author Jeremiah
 */
public class CommissionFrame extends javax.swing.JFrame {

   
    public CommissionFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(121, 194, 234));
        jPanel1.setLayout(null);
        jPanel1.add(jTextField1);
        jTextField1.setBounds(60, 30, 130, 24);
        jPanel1.add(jTextField2);
        jTextField2.setBounds(60, 80, 130, 24);
        jPanel1.add(jTextField3);
        jTextField3.setBounds(60, 130, 130, 24);
        jPanel1.add(jTextField4);
        jTextField4.setBounds(60, 180, 130, 24);
        jPanel1.add(jTextField5);
        jTextField5.setBounds(60, 230, 130, 24);

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(90, 270, 80, 32);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Commission Gen 5");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 210, 250, 16);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Commission Gen 1");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 10, 250, 16);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Commission Gen 2");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(0, 60, 250, 16);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Commission Gen 3");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(0, 110, 250, 16);

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Commission Gen 4");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(0, 160, 250, 16);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    String scom1=jTextField1.getText();
    String scom2=jTextField2.getText();
    String scom3=jTextField3.getText();
    String scom4=jTextField4.getText();
    String scom5=jTextField5.getText();
    
    double com1=Double.parseDouble(scom1);
    double com2=Double.parseDouble(scom2);
    double com3=Double.parseDouble(scom3);
    double com4=Double.parseDouble(scom4);
    double com5=Double.parseDouble(scom5);
    double sumcom=com1+com2+com3+com4+com5;
        
    
    if(!jTextField1.equals("") && !jTextField2.equals("") && !jTextField3.equals("") && !jTextField4.equals("") && !jTextField5.equals("") && sumcom<0.8){
    MyTree.setGen1Commission(Double.parseDouble(jTextField1.getText()));
    MyTree.setGen2Commission(Double.parseDouble(jTextField2.getText()));
    MyTree.setGen3Commission(Double.parseDouble(jTextField3.getText()));
    MyTree.setGen4Commission(Double.parseDouble(jTextField4.getText()));
    MyTree.setGen5Commission(Double.parseDouble(jTextField5.getText()));
    MyTree.updateAdminConfigFile();
    dispose();
    }
    else{
        JOptionPane.showMessageDialog(null, "Please make sure the total commission for all generations does NOT EXCEED 80%",  " Trying to lose money ?", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_jButton1ActionPerformed


    public void runCommissionFrame() {
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CommissionFrame commissionframe= new CommissionFrame();
                commissionframe.setVisible(true);
                commissionframe.setLocationRelativeTo(null);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
